### ISSUE TITLE
Need to add support for paste image handling like whatsapp input field

### ISSUE THREAD

**Issue by Usman4Whizpool** [KennethTsang/GrowingTextView#15]
Hi there

Just noticed that your code do not support paste image to input field is used in messaging app.
Like in whatsapp copy image from any place (check in iphone) and try long press on input field of any chat screen, paste option will appear and on selecting that.. it will allow you to paste, image copied will be shown in other view..

for such handling in you code i modified the class ""

added two new delegates and two methods

Delegates: 

 ```
@objc optional func textViewPasteImage(_ pastedImage:UIImage)
    @objc optional func textViewPasteText(_ pastedText:String)
```

methods
```
override open func canPerformAction(_ action: Selector, withSender sender: Any?) -> Bool {
        
        if (action == #selector(paste(_:))) {
            return true
        }
        else if self.text.characters.count > 0 {
            if (action == #selector(select(_:)) || action == #selector(selectAll(_:)) || action == #selector(cut(_:)))
            {
                return true
            }
        }
        
        return false
    }
    
    override open func paste(_ sender: Any?) {
        //
        if (UIPasteboard.general.string != nil) {
            
            if let delegate = delegate as? GrowingTextViewDelegate {
                delegate.textViewPasteText!(UIPasteboard.general.string!)
            }
        }
        else if UIPasteboard.general.image != nil {
            
            if let delegate = delegate as? GrowingTextViewDelegate {
                    delegate.textViewPasteImage!(UIPasteboard.general.image!)
            }
        }
    }
```

These might not be a perfect solution.... i request please can you add such type for handling
to you code also...

**Comment by KennethTsang** [comment]
@Usman4Whizpool Thanks for your suggestion, but we are not planned to implement this feature because it is out of scope of this textview. The better way is to do it in a subclass of GrowingTextView.
