### ISSUE TITLE
Use inside UITableViewCell

### ISSUE THREAD

**Issue by SemenovAlexander** [KennethTsang/GrowingTextView#16]
Hello, thanks for the great library!

I'm trying to use it inside UITableViewCell with all edges pinned to edges of cell, so tableviewcell should grow height with textview size change. 
I've adopted self sizing textview, as described here
http://candycode.io/self-sizing-uitextview-in-a-uitableview-using-auto-layout-like-reminders-app/

While it works fine with regular UITextView, when I change it to GrowingTextView - I constantly receive following error with constraints  (it seems GrowingTextView tries to update height costraint before it should do so):

```
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x60000009da10 UILabel:0x7fa954e23b00'\U0421\U043e\U0445\U0440\U0430\U043d\U0438\U0442\U044c \U0432 \U0448\U0430\U0431\U043b\U043e\U043d\U044b'.height == 30   (active)>",
    "<NSLayoutConstraint:0x61000009f1d0 V:[UILabel:0x7fa954e23b00'\U0421\U043e\U0445\U0440\U0430\U043d\U0438\U0442\U044c \U0432 \U0448\U0430\U0431\U043b\U043e\U043d\U044b']-(7)-|   (active, names: '|':UITableViewCellContentView:0x7fa954e224c0 )>",
    "<NSLayoutConstraint:0x61000009e0a0 V:|-(7)-[UILabel:0x7fa954e23b00'\U0421\U043e\U0445\U0440\U0430\U043d\U0438\U0442\U044c \U0432 \U0448\U0430\U0431\U043b\U043e\U043d\U044b']   (active, names: '|':UITableViewCellContentView:0x7fa954e224c0 )>",
    "<NSLayoutConstraint:0x61800009afe0 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x7fa954e224c0.height == 43.5   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000009da10 UILabel:0x7fa954e23b00'Сохранить в шаблоны'.height == 30   (active)>
```

**Comment by KennethTsang** [comment]
In my experience, this kind of conflict happened in between the view initializing and the frame is not yet finalized. According to your error message, you may try to lower the height constraint priority (set priority to 999) of the UILabel.

**Comment by KennethTsang** [comment]
Hope you have fixed the problem. I am going to close the issue.

**Comment by cliftonlabrum** [comment]
@SemenovAlexander I'm having this same issue. Did you ever get it to work?

**Comment by Kazushi-Uemura** [comment]
I have the same problem. How do I get rid of the error?
