### ISSUE TITLE
Top and bottom insets sometimes appear to be incorrect.

### ISSUE THREAD

**Issue by mattftraceme** [KennethTsang/GrowingTextView#18]
Using the sample app, when the GrowingTextView expands from one line to two lines, there is way too much padding underneath the text, and way too little above it. If you keep typing and expand to three lines, the padding is still off, but not as badly. What is really interesting though is that if you backspace back to two lines, the padding is perfect. See attached screenshots.

My initial thought was that this had to do with the UITextView.textContainerInset, or setting the scroll position. However, if you use Xcode to Debug View Hierarchy you can see what is going on. The TextView has a subview of type _UITextContainerView, and that is obviously offset by about 10 pixels above where it should be. However, using the inspector, that view claims that its frame is at 0,0.

Unfortunately I have no idea how to fix this -- it seems like an iOS bug. I am seeing it building with Xcode 9 on iOS 11 and iOS 10 devices.

![screen shot 2017-10-27 at 2 01 04 pm](https://user-images.githubusercontent.com/30244433/32125698-0edc1656-bb22-11e7-855f-425a7a3039e6.png)
![screen shot 2017-10-27 at 2 02 59 pm](https://user-images.githubusercontent.com/30244433/32125704-1439f712-bb22-11e7-98c3-27c14e84e565.png)

**Comment by KennethTsang** [comment]
Thanks @mattftraceme , as you said, it should be a bug of Swift4. I found a quick workaround for this by making some change on height constraint again after expanding the textview (e.g. add 0.0000001 px). I have submitted a new version for this.
