### ISSUE TITLE
Using non-default textContainerInset value, initial text is misplaced

### ISSUE THREAD

**Issue by mattftraceme** [KennethTsang/GrowingTextView#19]
Thanks for fixing the previous issue so quickly! Here is another one...

In GrowingTextView-Example, Example2.viewDidLoad(), add this line:
        textView.textContainerInset = UIEdgeInsets(top: 10, left: 10, bottom: 10, right: 10)

See the first screen shot for the result. The placeholder text is closer to the top than bottom, it is expected to be centered.

The second screenshot shows the results after typing text until the line wraps, then backspacing to clear all text. The placeholder location is correct.

![screen shot 2017-10-31 at 9 43 11 am](https://user-images.githubusercontent.com/30244433/32237222-a35cd85e-be21-11e7-8abc-2dcabf9ef765.png)

![screen shot 2017-10-31 at 9 43 24 am](https://user-images.githubusercontent.com/30244433/32237229-a96f5348-be21-11e7-8ce4-f097c4c184bf.png)

**Comment by KennethTsang** [comment]
I have fixed it by updating the logic in layoutSubviews. This update also fixed the previous issue #18 , so that the dirty workaround (add height by 0.0000001 px) is no longer needed.

Thanks @mattftraceme !
