### ISSUE TITLE
Example 2 & 3 failed under iOS 11

### ISSUE THREAD

**Issue by bayareahank** [KennethTsang/GrowingTextView#21]
Built directly on top of example storyboard, example 1 runs fine, but both 2 & 3 failed. 

Both would complain of height constraints missing. Yet after resolving conflicts by adding missing constraints, textView wouldn't grow as expected. Wondering whether we need to do something more for iOS 11.

**Comment by justdan0227** [comment]
Have you tried it lately?  I just did yesterday and got all 3 examples to work

**Comment by KennethTsang** [comment]
@bayareahank I have tried in Xcode 9.2 and iOS 11, everything is working fine.
