### ISSUE TITLE
Autolayout Failed to Render

### ISSUE THREAD

**Issue by Mahan3340** [KennethTsang/GrowingTextView#31]
error: IB Designables: Failed to render and update auto layout status for UIView (i5M-Pr-FkT): dlopen(GrowingTextView.framework, 1): no suitable image found.  Did find:
	GrowingTextView.framework: required code signature missing for 'GrowingTextView.framework'

getting this error for days and nothing could fix it , any idea ?

**Comment by Mahan3340** [comment]
this is new Cocoapod version Issues , fixed it by adding below code to pods if anyone encountered it 

```
post_install do |installer|
      installer.pods_project.build_configurations.each do |config|
          config.build_settings.delete('CODE_SIGNING_ALLOWED')
          config.build_settings.delete('CODE_SIGNING_REQUIRED')
      end
  end
```

**Comment by rpdever** [comment]
Thanks! This helps a lot!
