### ISSUE TITLE
Not Compatible with Swift 4.2

### ISSUE THREAD

**Issue by StellarKuldeep** [KennethTsang/GrowingTextView#40]
When I update pod with `pod 'GrowingTextView', '~> 0.6'` it gives me error like below.

![screen shot 2018-09-22 at 2 15 46 pm](https://user-images.githubusercontent.com/38131385/45915424-2b7d9600-be72-11e8-9bb6-1ee4f9492a9b.png)

How to fix this?
Thanks in advance.

**Comment by denistrofimov** [comment]
+1

**Comment by KennethTsang** [comment]
Problem fixed.
You can now use `pod 'GrowingTextView', '0.6.1'` to install. Thanks!
