### ISSUE TITLE
Adjusting Text View Inset 

### ISSUE THREAD

**Issue by chuninator** [KennethTsang/GrowingTextView#47]
Having an issue when wanting to adjust the inset of the text. I'd like to add a padding to the inside so the text starts further away from the edge of the text view.  Currently the text indicator is too close to edge. 

*Current* 
![Screen Shot 2019-04-01 at 9 48 35 PM](https://user-images.githubusercontent.com/15239417/55385011-e8a71580-54c7-11e9-95a3-5c5729410d52.png)

Trying to change the content inset gives this outcome:
```
messageField.textContainerInset = UIEdgeInsets(top: 0, left: 0.5, bottom: 0, right: 0)
```
![Screen Shot 2019-04-01 at 9 43 02 PM](https://user-images.githubusercontent.com/15239417/55384731-2ce5e600-54c7-11e9-890a-02098e3fc84c.png)
 
Ideas?

**Comment by KennethTsang** [comment]
Try either one of these:
`textView.textContainer.lineFragmentPadding = 10`
`textView.textContainerInset.left = 10`

**Comment by chuninator** [comment]
Thank you @KennethTsang. 
`messageField.textContainer.lineFragmentPadding = 10 `worked.
