### ISSUE TITLE
ReadMe says Swift 5 Podspec sets Swift 4

### ISSUE THREAD

**Issue by mihirpmehta** [KennethTsang/GrowingTextView#49]
It's mentioned in Readme.md file that for Swift 5 you need to use 0.7 version. But if i use that version. It's settings still shows Swift 4 as language and compiler throws error that Swift 5 conversion is available

**Comment by KennethTsang** [comment]
Project build setting has been fixed. Please use 0.7.1

**Comment by mihirpmehta** [comment]
Thank you
