### ISSUE TITLE
App crashed on XCode 11.2

### ISSUE THREAD

**Issue by sailendra85** [KennethTsang/GrowingTextView#53]
I have app crashed by using this library, the reason is "Could not instantiate class named _UITextLayoutView because no class named _UITextLayoutView was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target)". If there is any body have same issue please let me know how to resolved this issue, thanks

**Comment by Shawnees** [comment]
Le crash est fix dans Xcode 11.2.1 GM

**Comment by KennethTsang** [comment]
Thanks @Shawnees
