### ISSUE TITLE
Text overrides placeholder Swift 3

### ISSUE THREAD

**Issue by AndreiBoariu** [KennethTsang/GrowingTextView#6]
Hey, 

**First of all, many many thanks for your contribution to this pod. It works amazing ;)**

I have a case, when I need to EDIT account description, so in edit case, I have to fill description, but it overrides placeholder text.
![screen shot 2017-02-28 at 10 49 50 am](https://cloud.githubusercontent.com/assets/5098683/23398038/a56826ba-fda3-11e6-8937-063766bf8c6d.png)

Any idea how to solve this?

`//>>    Set textview properties`
` txvBio.maxLength                      = 250`
`txvBio.placeHolder                    = "Short bio (up to 250 characters)"`

`if isEditingAccount {`
`     self.txvBio.text        = curAccount.descriptionDetails`
`}`

If `self.txvBio.placeHolder = nil` then when delete all text, placeholder no longer appear.

Any ideas ?

Thanks in advance!

Andy

**Comment by AndreiBoariu** [comment]
Hey, found solution ;)

In edit case, just set the text first, then set placeholder. 
Its working nice ;)

Thanks ;)

**Comment by KennethTsang** [comment]
Issue fixed. Placeholder will be redrawn after set text.
Thanks!
