### ISSUE TITLE
 infinite layoutSubviews loop

### ISSUE THREAD

**Issue by vitalrum** [KennethTsang/GrowingTextView#9]
Hi, thanks for good work.
But... bug:
just enter fast some lines like this:
http://joxi.ru/DrlBkR0i4bW4j2

layoutSubviews infinite calls, CPU usage 100%

**Comment by KennethTsang** [comment]
It's caused by sizeThatFits triggers layoutSubviews everytime. I added a checking to prevent calling sizeThatFits if text and orientation didn't change.

Thanks!

**Comment by vitalrum** [comment]
Thank you , so fast fix!
